name: Run maven tests

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  call-workflow-maven-build:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build-lib.yml@main
    with:
      java-version: 21
      sbom-path: ./
    secrets: inherit